"""initial schema

Revision ID: eddfe0ad9441
Revises:
Create Date: 2026-09-14

Hand-written to match src/app/*/models.py (build order step 1). Not
autogenerated — Docker wasn't available in this environment to run
`alembic revision --autogenerate` against real Postgres. Re-run
`alembic check` (or autogenerate a follow-up revision) against a live
database before trusting this as the final word; it should produce no diff
if this migration and the models agree.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "eddfe0ad9441"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _timestamp_columns() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    ]


def upgrade() -> None:
    op.create_table(
        "outbox_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("aggregate_type", sa.String(64), nullable=False),
        sa.Column("aggregate_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(128), nullable=False),
        sa.Column("payload", postgresql.JSONB, nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamp_columns(),
    )

    op.create_table(
        "venues",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        *_timestamp_columns(),
    )

    op.create_table(
        "sections",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "venue_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("venues.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(128), nullable=False),
        *_timestamp_columns(),
    )

    op.create_table(
        "seats",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "section_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sections.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("row_label", sa.String(8), nullable=False),
        sa.Column("seat_number", sa.Integer, nullable=False),
        *_timestamp_columns(),
        sa.UniqueConstraint("section_id", "row_label", "seat_number", name="uq_seat_position"),
    )

    op.create_table(
        "events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        *_timestamp_columns(),
    )

    op.create_table(
        "shows",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "event_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("events.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "venue_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("venues.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        *_timestamp_columns(),
    )

    seat_status = postgresql.ENUM("AVAILABLE", "HELD", "BOOKED", name="seat_status")

    op.create_table(
        "seat_inventory",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "show_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("shows.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "seat_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("seats.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "status", seat_status, nullable=False, server_default="AVAILABLE"
        ),
        sa.Column("held_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("hold_expires_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamp_columns(),
        sa.UniqueConstraint("show_id", "seat_id", name="uq_seat_inventory_show_seat"),
        sa.CheckConstraint(
            "status != 'HELD' OR (held_by IS NOT NULL AND hold_expires_at IS NOT NULL)",
            name="ck_held_requires_holder_and_expiry",
        ),
    )

    booking_status = postgresql.ENUM(
        "PENDING", "CONFIRMED", "CANCELLED", "EXPIRED", name="booking_status"
    )

    op.create_table(
        "bookings",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "show_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("shows.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "status", booking_status, nullable=False, server_default="PENDING"
        ),
        sa.Column("idempotency_key", sa.String(128), nullable=False, unique=True),
        *_timestamp_columns(),
    )

    op.create_table(
        "booking_seats",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "booking_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("bookings.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "seat_inventory_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("seat_inventory.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        *_timestamp_columns(),
        sa.UniqueConstraint("seat_inventory_id", name="uq_booking_seat_inventory"),
    )

    payment_status = postgresql.ENUM(
        "CREATED", "AUTHORIZED", "CAPTURED", "FAILED", "REFUNDED", name="payment_status"
    )

    op.create_table(
        "payments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "booking_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("bookings.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("provider_ref", sa.String(128), nullable=False, unique=True),
        sa.Column("amount", sa.Numeric(10, 2), nullable=False),
        sa.Column(
            "status", payment_status, nullable=False, server_default="CREATED"
        ),
        *_timestamp_columns(),
    )


def downgrade() -> None:
    op.drop_table("payments")
    op.drop_table("booking_seats")
    op.drop_table("bookings")
    op.drop_table("seat_inventory")
    op.drop_table("shows")
    op.drop_table("events")
    op.drop_table("seats")
    op.drop_table("sections")
    op.drop_table("venues")
    op.drop_table("outbox_events")

    postgresql.ENUM(name="payment_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="booking_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="seat_status").drop(op.get_bind(), checkfirst=True)
